# -*- coding: utf-8 -*-
"""Altair - Scatterplot with Tooltip - MOM 2022W22.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Q6K_d98ubHbWDfGmxtEduQlgk5EJQz_p
"""

import pandas as pd
import altair as alt

df = pd.read_csv("https://raw.githubusercontent.com/hmreumann/ecd2022a/main/data/election-cycle-fundraising-2.csv")

alt.Chart(df).mark_circle(size=40, opacity=0.5).encode(
    x='raised',
    y='spent',
    color='party',
    tooltip=['member', 'chamber', 'party', 'raised', 'spent']
).interactive()

alt.Chart(df).mark_tick().encode(
    x="raised",
    y="party",
    color="party",
    tooltip=['member', 'chamber', 'party', 'raised', 'spent']
).interactive()